DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS votes CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  created_by INTEGER REFERENCES users(id) ON DELETE CASCADE,
  question_text VARCHAR(255) NOT NULL,
  created_at TIMESTAMP,
  end_date DATE,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  poll INTEGER REFERENCES polls(id),
  option_text VARCHAR(255) 
);

CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  user_vote INTEGER REFERENCES options(id) ON DELETE CASCADE,
  voted_at TIMESTAMP
);